### ISSUE TITLE
Release of WebLabel Player for visualizing the OSDaR23 dataset

### ISSUE THREAD

**Issue by xavidzo** [Vicomtech/weblabel#1]
Hello @amujikaVicomtech , are you planing to release soon the WebLabel Player to visualize the railway dataset? https://data.fid-move.de/en/dataset/osdar23
Or can you please give an estimated date for when the tool will be available? Thanks a lot for the awesome work

**Comment by amujikaVicomtech** [comment]
Hello @xavidzo
Hopefully it will be released this week.
