### ISSUE TITLE
How to run the application in Docker?

### ISSUE THREAD

**Issue by xavidzo** [Vicomtech/weblabel#2]
Hello @amujikaVicomtech, I was able to load the docker image based on the .tar file file you provided in the Release, so if do `docker image list` I am able to see the image as `web-label:v2.0.0`.

Then I guess, I have to run the container based on this image like so (?): `docker run -p 8080:8080 web-label:v2.0.0 `
And this is the output I get afterwards:

> /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
> 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
> 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
> /docker-entrypoint.sh: Configuration complete; ready for start up
> 2023/05/08 08:26:16 [notice] 1#1: using the "epoll" event method
> 2023/05/08 08:26:16 [notice] 1#1: nginx/1.23.4
> 2023/05/08 08:26:16 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
> 2023/05/08 08:26:16 [notice] 1#1: OS: Linux 5.19.0-41-generic
> 2023/05/08 08:26:16 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> 2023/05/08 08:26:16 [notice] 1#1: start worker processes
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 28
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 29
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 30
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 31
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 32
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 33
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 34
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 35
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 36
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 37
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 38
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 39
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 40
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 41
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 42
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 43
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 44
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 45
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 46
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 47
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 48
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 49
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 50 
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 51
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 52
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 53
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 54
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 55
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 56
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 57
> 2023/05/08 08:26:16 [notice] 1#1: start worker process 58

However, when I open in my browser (Chrome) http://localhost:8080/ it still says 

> This site can't be reached

Can you please tell me if I am still missing something for executing the container correctly? Thank you
(btw, in Windows the tool works fine, but I really need it for Linux)

**Comment by gpierolaVicomtech** [comment]
Hi @xavidzo, the application is launched in port `80` in the container, so you should run `docker run -p 8080:80 -d web-label:v2.0.0`.
